version: "2"

run:
  timeout: 5m
  go: "1.25"
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - ifElseChain
        - unlambda

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - spindle

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
