# Strict linting configuration for CI/CD or gradual improvement
# Copy this to pyproject.toml when ready for stricter standards

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I", "N", "UP", "YTT", "S", "BLE", "FBT", "B", "A", "COM", "C4", "DTZ", "T10", "EM", "EXE", "FA", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "ARG", "PTH", "TD", "FIX", "ERA", "PD", "PGH", "PL", "TRY", "FLY", "NPY", "AIR", "PERF", "FURB", "LOG", "RUF"]

# Minimal suppressions - only the truly pragmatic ones
ignore = [
    "S101",     # Use of assert (needed in tests)
    "T201",     # Print found (CLI tool)
    "PLR0913",  # Too many arguments (sometimes unavoidable)
    "E501",     # Line length (formatter handles this)
    "ARG001",   # Unused argument (required for protocols/callbacks)
]

# Per-file ignores for specific cases
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S603", "S607"]  # Allow assert and subprocess in tests
"src/spindle/cli.py" = ["T201"]  # Allow print in CLI
"src/spindle/processor.py" = ["PLR0915", "C901"]  # Complex but necessary