package subtitle

import (
	"context"
	"fmt"
	"log/slog"
	"math"
	"os"
	"path/filepath"
	"strings"

	"github.com/five82/spindle/internal/llm"
	"github.com/five82/spindle/internal/logs"
	"github.com/five82/spindle/internal/srtutil"
)

// creditsWindowSeconds is how far before the end of the video the
// end-credits region is assumed to start, for both the LLM prompt hint and
// the removal-cap guardrail.
const creditsWindowSeconds = 420.0

// creditsRegionStart returns when the end-credits region is assumed to
// begin. The window is creditsWindowSeconds capped at 10% of runtime so
// short TV content does not get a large share of its running time treated
// as credits (where removals are uncapped). Unknown duration (<= 0) means
// no credits region.
func creditsRegionStart(videoSeconds float64) float64 {
	if videoSeconds <= 0 {
		return math.Inf(1)
	}
	return videoSeconds - math.Min(creditsWindowSeconds, videoSeconds*0.1)
}

// auditRemovalCapFailureReason is the AuditStats.FailureReason set when
// resolved removals exceed the non-credits removal guardrail cap.
const auditRemovalCapFailureReason = "non-credits removal cap exceeded"

// subtitleAuditSystemPrompt instructs the LLM to flag only obvious WhisperX
// transcription errors in a display subtitle track. Keep the semantics
// exactly as validated; adjust only formatting.
const subtitleAuditSystemPrompt = `You are auditing an English SRT subtitle file generated by WhisperX (automatic speech recognition). WhisperX makes transcription errors. Your job is to find OBVIOUS errors only. A false positive (bad "correction") is far worse than a missed error. When in doubt, skip.

FLAG ONLY these categories:
- hallucination: a short phrase like "Thank you.", "Thanks for watching.", "Subscribe." appearing repeatedly in isolation (large timestamp gaps around it, not part of a conversation)
- credits_music: lyric cues in the end-credits region after all narrative dialogue has ended. The final scene's real dialogue often continues into and interleaves with the credits song: remove only lyric lines, never conversational exchanges between characters, even inside the end-credits region.
- music_bleed: soundtrack lyrics mid-film transcribed as dialogue (poetic/verse-chorus phrasing that does not fit the scene's conversation). PRESERVE diegetic singing: characters singing on-screen, performances, karaoke, plot-relevant lyrics. NEVER remove songs playing over the opening titles or title sequence; leave them alone. When unsure, skip.
- garbled: text that is clearly not real English or makes no sense in any context. If garbled text is mid-film speech, propose a replacement only when the correct wording is unambiguous; NEVER remove garbled speech cues.
- homophone: wrong word where surrounding text makes the correct word unambiguous (e.g. their/there, "would of" for "would have")
- broken: empty cues, whitespace/punctuation-only cues, orphaned music symbols
- repeated: adjacent cues with identical text and overlapping timestamps
- encoding: mojibake / corrupted characters

DO NOT flag: proper-noun spellings you cannot verify from context, grammar, punctuation style, capitalization, line breaks, rephrasing, timing, suspected mishearings where the correct word is not unambiguous, ambiguous short exclamations ("Oh!", "No!"), or diegetic/plot-relevant song lyrics.

Return JSON: {"edits": [{"index": <cue index>, "current_text": "<exact current text>", "action": "remove" | "replace", "replacement": "<new text if replace>", "category": "<category>", "reason": "<brief>", "confidence": "high" | "medium"}]}

Return {"edits": []} if nothing qualifies. current_text must exactly match the cue text. List every affected cue as its own edit: when a run of consecutive cues qualifies (for example an end-credits song), emit one edit per cue in the run; never summarize a range in a single edit. Never emit a replace whose replacement equals the current text.`

// AuditStats reports the outcome of the LLM display-subtitle audit.
// Result "rejected" means the whole response was discarded by the removal-cap
// guardrail; unlike "skipped"/"failed" it routes the item to review.
type AuditStats struct {
	Result        string // "applied" | "clean" | "skipped" | "failed" | "rejected"
	Applied       int
	Dropped       int
	FailureReason string // set when Result is "skipped", "failed", or "rejected"
}

// auditParams configures a single audit run.
type auditParams struct {
	DisplayPath  string  // SRT file to audit and rewrite in place
	VideoSeconds float64 // full video duration; <= 0 means unknown
	MediaContext string  // e.g. `the movie "Air" (2023)` or `Breaking Bad S01E01`
	EpisodeKey   string  // for logging only
}

// auditEdit is a single proposed edit as returned by the LLM.
type auditEdit struct {
	Index       int    `json:"index"`
	CurrentText string `json:"current_text"`
	Action      string `json:"action"`      // "remove" | "replace"
	Replacement string `json:"replacement"` // for replace
	Category    string `json:"category"`
	Confidence  string `json:"confidence"` // "high" | "medium"
	Reason      string `json:"reason"`
}

// auditResponse is the JSON response schema requested from the LLM.
type auditResponse struct {
	Edits []auditEdit `json:"edits"`
}

// resolvedEdit is an auditEdit that has been matched to a specific cue and
// passed validity checks. CueIndex is a position into the cues slice that
// resolution operated on (0-based), not the cue's own Index field.
type resolvedEdit struct {
	CueIndex    int
	Action      string // "remove" | "replace"
	Replacement string // resolved, wrapped replacement text; only for "replace"
	Category    string
	Reason      string
}

// auditDisplaySRT audits a display SRT file with the LLM and rewrites it in
// place with any applied edits. It never returns an error: every failure
// path is logged and reflected in the returned stats, and the caller
// continues with the unaudited file.
func auditDisplaySRT(ctx context.Context, client *llm.Client, logger *slog.Logger, params auditParams) AuditStats {
	logger = logs.Default(logger)

	if client == nil {
		logger.Debug("subtitle audit skipped",
			"event_type", "subtitle_audit_skipped",
			"error_hint", "llm not configured",
			"episode_key", params.EpisodeKey,
		)
		return AuditStats{Result: "skipped", FailureReason: "llm not configured"}
	}

	cues, err := srtutil.ParseFile(params.DisplayPath)
	if err != nil {
		warnAuditSkipped(logger, "subtitle audit skipped", "could not read display subtitle", err, params.EpisodeKey)
		return AuditStats{Result: "skipped", FailureReason: err.Error()}
	}
	if len(cues) == 0 {
		return AuditStats{Result: "skipped", FailureReason: "no cues found"}
	}

	userPrompt := buildAuditUserPrompt(cues, params)

	var resp auditResponse
	if err := client.CompleteJSON(ctx, subtitleAuditSystemPrompt, userPrompt, &resp); err != nil {
		warnAuditSkipped(logger, "LLM subtitle audit request failed", "llm api error", err, params.EpisodeKey)
		return AuditStats{Result: "failed", FailureReason: err.Error()}
	}

	proposed := len(resp.Edits)
	resolved, dropped := resolveAuditEdits(cues, resp.Edits)

	if len(resolved) == 0 {
		logger.Info("subtitle audit complete",
			"event_type", "subtitle_audit_complete",
			"episode_key", params.EpisodeKey,
			"proposed", proposed,
			"applied", 0,
			"dropped", dropped,
		)
		return AuditStats{Result: "clean", Dropped: dropped}
	}

	if exceeded, nonCreditsRemovals, cap := auditRemovalCap(cues, resolved, params.VideoSeconds); exceeded {
		logger.Warn("subtitle audit rejected",
			"event_type", "subtitle_audit_rejected",
			"error_hint", fmt.Sprintf("non_credits_removals=%d exceeds cap=%d", nonCreditsRemovals, cap),
			"impact", "subtitle not audited; WhisperX errors may remain",
			"episode_key", params.EpisodeKey,
			"proposed", proposed,
		)
		return AuditStats{Result: "rejected", FailureReason: auditRemovalCapFailureReason}
	}

	for _, r := range resolved {
		cue := cues[r.CueIndex]
		attrs := []any{
			"decision_type", "subtitle_audit_edit",
			"decision_result", r.Action,
			"decision_reason", fmt.Sprintf("%s: %s", r.Category, r.Reason),
			"episode_key", params.EpisodeKey,
			"cue_index", cue.Index,
			"cue_text", cue.Text,
		}
		if r.Action == "replace" {
			attrs = append(attrs, "replacement", r.Replacement)
		}
		logger.Info("subtitle audit edit applied", attrs...)
	}

	newCues := applyResolvedEdits(cues, resolved)
	if err := writeSRTAtomic(params.DisplayPath, newCues); err != nil {
		warnAuditSkipped(logger, "subtitle audit skipped", "could not write audited subtitle", err, params.EpisodeKey)
		return AuditStats{Result: "failed", FailureReason: err.Error()}
	}

	logger.Info("subtitle audit complete",
		"event_type", "subtitle_audit_complete",
		"episode_key", params.EpisodeKey,
		"proposed", proposed,
		"applied", len(resolved),
		"dropped", dropped,
	)

	return AuditStats{Result: "applied", Applied: len(resolved), Dropped: dropped}
}

// warnAuditSkipped logs the shared degraded-audit warning shape for the
// error paths that leave the subtitle unaudited.
func warnAuditSkipped(logger *slog.Logger, msg, hint string, err error, episodeKey string) {
	logger.Warn(msg,
		"event_type", "subtitle_audit_skipped",
		"error_hint", hint,
		"impact", "subtitle not audited; WhisperX errors may remain",
		"error", err,
		"episode_key", episodeKey,
	)
}

// resolveAuditEdits matches each proposed edit to a cue, applies dedupe and
// validity rules, and returns the edits that survive. dropped counts every
// edit that did not survive resolution.
func resolveAuditEdits(cues []srtutil.Cue, edits []auditEdit) ([]resolvedEdit, int) {
	norm := make([]string, len(cues))
	for i, c := range cues {
		norm[i] = normalizeAuditText(c.Text)
	}
	posByIndex := make(map[int]int, len(cues))
	for i, c := range cues {
		posByIndex[c.Index] = i
	}
	byText := make(map[string][]int, len(cues))
	for i, n := range norm {
		byText[n] = append(byText[n], i)
	}

	var resolved []resolvedEdit
	dropped := 0
	used := make(map[int]bool, len(edits))

	for _, e := range edits {
		if e.Action != "remove" && e.Action != "replace" {
			dropped++
			continue
		}

		normCurrent := normalizeAuditText(e.CurrentText)
		pos := -1
		if p, ok := posByIndex[e.Index]; ok && norm[p] == normCurrent {
			pos = p
		} else if matches := byText[normCurrent]; len(matches) == 1 {
			pos = matches[0]
		} else if len(matches) > 1 {
			for _, m := range matches {
				if cues[m].Index == e.Index {
					pos = m
					break
				}
			}
		}
		if pos == -1 {
			dropped++
			continue
		}
		if used[pos] {
			dropped++
			continue
		}

		if e.Action == "replace" {
			// Models echo the prompt's literal \n cue serialization back in
			// replacement text; normalize it away before it reaches the SRT.
			replacement := normalizeAuditText(e.Replacement)
			if e.Confidence != "high" || replacement == "" {
				dropped++
				continue
			}
			if replacement == normCurrent {
				dropped++
				continue
			}
			wrapped, _ := wrapDisplayCueText(replacement)
			resolved = append(resolved, resolvedEdit{
				CueIndex:    pos,
				Action:      "replace",
				Replacement: wrapped,
				Category:    e.Category,
				Reason:      e.Reason,
			})
		} else {
			resolved = append(resolved, resolvedEdit{
				CueIndex: pos,
				Action:   "remove",
				Category: e.Category,
				Reason:   e.Reason,
			})
		}
		used[pos] = true
	}

	return resolved, dropped
}

// applyResolvedEdits builds the final cue list: "remove" edits drop their
// cue, "replace" edits rewrite the cue text, everything else passes through
// unchanged. The result is re-indexed sequentially from 1.
func applyResolvedEdits(cues []srtutil.Cue, resolved []resolvedEdit) []srtutil.Cue {
	byCue := make(map[int]resolvedEdit, len(resolved))
	for _, r := range resolved {
		byCue[r.CueIndex] = r
	}

	out := make([]srtutil.Cue, 0, len(cues))
	for i, cue := range cues {
		r, ok := byCue[i]
		if !ok {
			out = append(out, cue)
			continue
		}
		if r.Action == "remove" {
			continue
		}
		cue.Text = r.Replacement
		out = append(out, cue)
	}
	for i := range out {
		out[i].Index = i + 1
	}
	return out
}

// auditRemovalCap reports whether resolved "remove" edits targeting cues
// outside the end-credits region exceed the guardrail cap of
// max(5, len(cues)/10).
func auditRemovalCap(cues []srtutil.Cue, resolved []resolvedEdit, videoSeconds float64) (exceeded bool, nonCreditsRemovals, cap int) {
	creditsStart := creditsRegionStart(videoSeconds)
	for _, r := range resolved {
		if r.Action != "remove" {
			continue
		}
		if cues[r.CueIndex].Start < creditsStart {
			nonCreditsRemovals++
		}
	}
	cap = len(cues) / 10
	if cap < 5 {
		cap = 5
	}
	exceeded = nonCreditsRemovals > cap
	return exceeded, nonCreditsRemovals, cap
}

// normalizeAuditText normalizes cue text for equality comparison against the
// LLM's current_text field and for sanitizing replacement text: case-sensitive,
// with the literal two-character sequence "\n" (as serialized in the prompt)
// treated as a space and all whitespace runs collapsed.
func normalizeAuditText(s string) string {
	return normalizeCueWhitespace(strings.ReplaceAll(s, `\n`, " "))
}

// buildAuditUserPrompt renders the cue list and media context for the LLM.
func buildAuditUserPrompt(cues []srtutil.Cue, params auditParams) string {
	var b strings.Builder
	b.WriteString("Subtitle file for ")
	b.WriteString(params.MediaContext)
	b.WriteString(".")
	if params.VideoSeconds > 0 {
		fmt.Fprintf(&b, " Video duration: %s. Cues starting after %s are likely in the end-credits region.",
			formatHMS(params.VideoSeconds), formatHMS(creditsRegionStart(params.VideoSeconds)))
	}
	b.WriteString("\n\nSUBTITLE CUES (index|start-->end|text, cue line breaks shown as \\n):\n")
	for i, c := range cues {
		if i > 0 {
			b.WriteString("\n")
		}
		text := strings.ReplaceAll(c.Text, "\n", `\n`)
		fmt.Fprintf(&b, "%d|%s-->%s|%s", c.Index, srtutil.FormatTimestamp(c.Start), srtutil.FormatTimestamp(c.End), text)
	}
	return b.String()
}

// formatHMS renders seconds as an SRT-style HH:MM:SS (no milliseconds).
func formatHMS(seconds float64) string {
	if seconds < 0 {
		seconds = 0
	}
	total := int(seconds)
	s := total % 60
	total /= 60
	m := total % 60
	h := total / 60
	return fmt.Sprintf("%02d:%02d:%02d", h, m, s)
}

// writeSRTAtomic renders cues and writes them to path atomically via a
// temp file in the same directory followed by rename.
func writeSRTAtomic(path string, cues []srtutil.Cue) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".subtitle-audit-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.WriteString(srtutil.Format(cues)); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("write temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close temp file: %w", err)
	}
	_ = os.Chmod(tmpPath, 0o644)
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename temp file: %w", err)
	}
	return nil
}
